"""Add bio and preferences to user

Revision ID: 5c8a2b032b1c
Revises: 
Create Date: 2026-05-07 02:55:37.919904

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5c8a2b032b1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
